### ISSUE TITLE
Parpadeo de las barras durante juego

### ISSUE THREAD

**Issue by Ciberox1** [BananaSlipDev/Rolling-Beats#21]
- Impacto: Alto
- Plataforma: Ordenador / Movil
- Descripción: Durante el juego, las canciones las cuales cuentan con barras de puntos tienen un parpadeo que en canciones largas pueden producir mareos

Pasos para reproducirlo:

1. Comenzar a jugar
2. Seleccionar una canción de larga duración

**Comment by Coexito** [comment]
Hemos rediseñado el funcionamiento de las notas largas para solucionar este y otros problemas. No más parpadeos 👍
