### ISSUE TITLE
Todo el feedback de si has acertado o fallado los pulsos, cambia en función del último intento

### ISSUE THREAD

**Issue by alexgrz** [BananaSlipDev/Rolling-Beats#22]
-Impacto: Bajo
-Plataforma: Todas
-Descripción: Cuando aciertas un pulso, te sale un "perfect" o un "great", si fallas, un "miss". Estos se convierten automáticamente en otros dependiendo del resultado del pulso que golpees en ese instante.
-Pasos para reproducirlo:
1.Empiezas el nivel.
2. Intentas golpear los pulsos.

**Comment by JuanJesus5** [comment]
Corroboramos que este pequeño error, también ha sido detectado en nuestro grupo. 

Pasos para reproducirlo:
1.-Jugar cualquier nivel.
2.-Tras pulsar una tecla y acertar sea great o perfect, si fallas posteriormente, el nombre cambia a Miss, además de generar un nuevo texto Miss.

**Comment by juanjomalouu** [comment]
Reworked :D
