### ISSUE TITLE
Barras mal colocadas si las erras

### ISSUE THREAD

**Issue by Ciberox1** [BananaSlipDev/Rolling-Beats#23]
- Impacto: Leve
- Plataforma: Ordenador
- Descripción: Cuando erras en una de las barras y luego le presionas, parte de la barra se coloca detrás del indicador de acierto
- Pasos para reproducirlo:

1. Seleccionar canción que contenga las barras
2. No darle en su debido tiempo
3. Darle después

**Comment by JuanJesus5** [comment]
Efectivamente, como mencionan los compañeros, se trata de un error visual que no afecta a la jugabilidad del juego, pero nosotros también lo hemos detectado.

**Comment by Coexito** [comment]
Hemos rediseñado el funcionamiento de las notas largas. Ahora, en lugar de un relleno se tendrán partículas. Este error no debería volver a ocurrir. Arreglado 👍
