### ISSUE TITLE
No detecta las notas dentro del área más grande

### ISSUE THREAD

**Issue by Ciberox1** [BananaSlipDev/Rolling-Beats#24]
- Impacto: Alto
- Plataforma: Móvil / Ordenador
- Descripción: No detecta las notas cuando estan dentro del area mas grande dejando unicamente el area mas pequeña para recibir las notas
- Pasos para reproducirlo:

1. Iniciar juego
2. Elegir canción
3. Dar a los objetivos en dentro del circulo grande pero fuera del pequeño

**Comment by JuanJesus5** [comment]
Como mencionan los compañeros, existe un problema con las cajas de colisiones de algunos sprites. Concretamente ocurre con las "Bolas de Navidad" y en menor medida, con los "Ojos Ensangrentados". 
Sin embargo, es importante destacar que no es un error que ocurra siempre, ya que en algunas partidas no ocurre.

**Comment by juanjomalouu** [comment]
El área que acepta notas es el área pequeña, no la grande. No es un error.
