### ISSUE TITLE
Reloj de juego desfasado

### ISSUE THREAD

**Issue by Ciberox1** [BananaSlipDev/Rolling-Beats#25]
- Impacto: Medio
- Plataforma: Móvil/Ordenador
- Descripción: Durante la partida, el reloj de juego empieza desfasado de modo que nunca empieza en cero.

- Pasos para reproducirlo:

1. Iniciar juego
2. Elegir canción

**Comment by Coexito** [comment]
El reloj de juego no empieza totalmente vacío, sino que se ve una pequeña parte del relleno, para indicar desde el inicio que se va a ir rellenando progresivamente. Hemos revisado el código y hecho pruebas, pero somos incapaces de detectar alguna ocasión en la que empiece lleno más de lo intencionado. Por ello suponemos que el error es referido a esta funcionalidad intencionada.
