### ISSUE TITLE
Fallo en el control de volumen master

### ISSUE THREAD

**Issue by Ciberox1** [BananaSlipDev/Rolling-Beats#26]
- Impacto: Medio
- Plataforma: Ordenador / Móvil
- Descripción: Si configuras el volumen para una canción y pausas el juego para reiniciar el nivel, el volumen vuelve a ser el máximo

- Pasos para reproducirlo:
1. Inicia el juego
2. Elige una canción
3. Pausa el juego
4. Resetea el nivel

**Comment by JuanJesus5** [comment]
Este bug, se produce de igual manera siguiendo estos pasos:
1.-Iniciar el juego.
2.-Configurar el audio por el usuario.
3.-Elegir una canción y acabar de jugar dicho nivel.
4.-Volver a jugar el juego con el botón de la flecha.

**Comment by juanjomalouu** [comment]
Fixed
