### ISSUE TITLE
Música de menú no suena a veces desde el inicio

### ISSUE THREAD

**Issue by Ciberox1** [BananaSlipDev/Rolling-Beats#28]
- Impacto: Bajo
- Plataforma: Ordenador (Firefox) / Móvil (Todos los navegadores)
- Descripción: No suena la música del menú hasta la selección de canción, e incluso ni siquiera en esa pantalla suena en el caso de Firefox, pero en Chrome por ejemplo suena a partir de que te loggeas
- Pasos para reproducirlo: No se cómo reproducirlo

**Comment by JuanJesus5** [comment]
Durante las pruebas realizadas por el grupo I, en las ocasiones que se ha testeado el juego, en ningún dispositivo y en ningún navegador, ha ocurrido este fallo.
