### ISSUE TITLE
El contador del reloj vuelve a reiniciarse al terminar el nivel.  

### ISSUE THREAD

**Issue by JuanJesus5** [BananaSlipDev/Rolling-Beats#29]
Impacto: bajo. 

Plataforma: PC, Windows, Chrome.

Descripción: Al terminar un nivel, cuando el reloj del tiempo da la vuelta completa, en ocasiones el reloj se reinicia a cero en vez quedarse relleno por completo. 

      En los niveles "Amongus" y "Lolito", el reloj, además de reiniciarse a 0, sigue avanzando durante unos segundos más.
      En los niveles "Dross" y "Laura Escanes", el reloj se reinicia a 0 y después salta hasta rellenar un cuarto del reloj completo.
      En los niveles "Dross" y "Vagrant", el reloj acaba bastante antes de haber terminado la canción.  

Pasos para reproducirlo:
1.- Jugar los niveles mencionados anteriormente.
2.- Esperar a que termine la canción.

**Comment by juanjomalouu** [comment]
Fixed :D
