### ISSUE TITLE
Parpadeo en la pantalla de una de las notas. 

### ISSUE THREAD

**Issue by JuanJesus5** [BananaSlipDev/Rolling-Beats#30]
Impacto: bajo.  

Plataforma: PC, Windows, Firefox 

Descripción: La pantalla muestra un frame que no se debería ver cada vez que va a aparecer un botón de los que hay que mantener presionado. Es un error algo molesto, pero, no afecta a la jugabilidad, aunque puede llegar a reducir la concentración de algunos jugadores.

Pasos para reproducirlo: 
1.-Jugar un nivel que tenga la mecánica del botón mantenido (ej. Contigo Pipo).
2.-Esperar a que aparezca un botón que haya que mantener presionado.

**Comment by Coexito** [comment]
Problema solucionado, tal y como se ha indicado en un entrada anterior para este error.
