### ISSUE TITLE
El combo no se quita al fallar en una nota de mantener pulsado.

### ISSUE THREAD

**Issue by JuanJesus5** [BananaSlipDev/Rolling-Beats#31]
Impacto: bajo.  

Plataforma: PC, Windows, Chrome.

Descripción: Cuando aparece una nota que haya que mantener pulsada, si aciertas el primer botón, aunque falles en el botón de cierre, o dejas de mantener pulsado, el multiplicador del combo no se reinicia a “x1” si no que mantiene su valor de aciertos a pesar de haber realizado un fallo.  

Pasos para reproducirlo: 
1.- Jugar un nivel con la mecánica de mantener pulsado (ej.: Contigo Pipo).
2.-Esperar a que aparezca un botón que haya que mantener presionado. 
3.-Acertar el inicio del botón mantenido, y dejar de mantener o fallar el botón de cierre.

**Comment by Coexito** [comment]
¡Hola! La nota de cierre de las notas está diseñada como un "salvavidas", por así decirlo, de forma que no pulsarla o levantar el botón en ella no reinicia el combo. De hecho, lo que se espera del usuario es que mantenga el botón durante el "relleno" de la nota larga y lo suelte justo al final, en la nota de cierre. Levantar el botón antes (pero no después) de la nota de cierre causaría el reinicio del combo.

Entendemos que se pueda interpretar como un error y agradecemos el feedback sobre el funcionamiento. Esperamos que, con el rediseño de las notas largas, se entienda mejor esta funcionalidad. Muchas gracias.
